with src_listings as (
    select *
    from {{ ref('src_listings') }}
)

select 
  listing_id,
  listing_url,
  listing_name,
  listing_description,
  neighborhood_overview,
  picture_url,
  host_id,
  host_url,
  host_name,
  host_since,
  host_location,
  host_about,
  host_response_time,
  safe_cast(replace(host_response_rate, '%', '') as int64) as host_response_rate,
  safe_cast(replace(host_acceptance_rate, '%', '') as int64) as host_acceptance_rate,
  host_is_superhost = 't' as host_is_superhost,
  host_thumbnail_url,
  host_picture_url,
  host_neighbourhood,
  host_listings_count,
  host_total_listings_count,
  host_has_profile_pic = 't' as host_has_profile_pic,
  host_identity_verified = 't' as host_identity_verified,
  neighbourhood_cleansed as listing_neighbourhood,
  neighbourhood_group_cleansed as listing_city,
  latitude,
  longitude,
  property_type,
  room_type,
  accommodates as maximum_capacity,
  coalesce(bathrooms, safe_cast(split(bathrooms_text, ' ')[0] as float64)) as bathrooms,
  bedrooms,
  beds,
  split(replace(replace(replace(amenities_array, '[', ''), ']', ''), '"', '')) as amenities,
  cast(replace(replace(price_str, '$', ''), ',', '') as float64) as daily_price,
  'EUR' as currency,
  minimum_nights,
  maximum_nights,
  has_availability = 't' as has_availability,
  availability_30,
  availability_60,
  availability_90,
  availability_365,
  number_of_reviews,
  number_of_reviews_l30d,
  number_of_reviews_ltm,
  first_review,
  last_review,
  review_scores_rating,
  review_scores_accuracy,
  review_scores_cleanliness,
  review_scores_checkin,
  review_scores_communication,
  review_scores_location,
  review_scores_value,
  license,
  instant_bookable = 't' as instant_bookable,
  reviews_per_month
from src_listings