version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table with Airnb listings data
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb', 'listings')
        
    columns:

      - name: listing_id
        description: Unique Airbnb identifier for the listing
        tests:
          - unique
          - not_null
      
      - name: listing_url
        description: Listing URL

      - name: listing_name
        description: Name of the listing

      - name: room_type
        description: Room classification of the listing (Entire home/apt, Private room, Shared room, Hotel room)
        tests:
          - accepted_values:
              values:
                - "Entire home/apt"
                - "Private room"
                - "Shared room"
                - "Hotel room"
      
      - name: minimum_nights
        description: The minimum amount of nights stay allowed for the listing
        tests:
          - positive_value

      - name: host_id
        description: The unique Aibnb identifier for the host
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: price
        description: The daily price of the stay
        tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .95
              min_value: 10 
              max_value: 500
          - dbt_expectations.expect_column_max_to_be_between:
              max_value: 5000 
              config:
                severity: warn

      - name: currency
        description: Currency of the price field

      - name: created_at
        description: Date in which the listing was created

      - name: updated_at
        description: Date of the last time the listing was updated
              
  - name: dim_hosts_cleansed
    columns:

      - name: host_id
        description: Unique Airbnb identifier for the host
        tests:
          - unique
          - not_null
      
      - name: host_name
        description: Name of the host

      - name: is_superhost
        description: Indicates if the host is classified as a Super Host
        tests:
          - not_null

      - name: created_at
        description: Date in which the record for the host was first created

      - name: updated_at
        description: Date of the last update in the host record

  - name: fact_reviews
    columns:

      - name: review_id
        description: Unique identifier of the review. Generated from the hashed concatenation of listing_id, review_date, reviewer_name and review_comments

      - name: listing_id
        description: Unique Airbnb identifier for the listing
        tests:
          - not_null

      - name: review_date
        description: Date of the review
        tests:
          - not_null

      - name: reviewer_name
        description: Name of the reviewer

      - name: review_comments
        description: Main comments left in the review

      - name: review_sentiment
        description: Overall review sentiment, as estipulated from a ML algorithm (negative, positive, neutral)
        tests:
          - accepted_values:
              values:
                - "negative"
                - "positive"
                - "neutral"
